# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-website
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.website.localhost.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-website
            port:
              number: 80